version: '3'
services:
  backend:
    image: nexus.482.solutions/woden_ui/woden_ui:latest
    container_name: woden_ui
    ports:
      - 3000:80
#    command: sh -c "sleep 5 && npm start"
    networks:
      - front_default

networks:
  front_default:
    external: true
